#server:
#  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    loadbalancer:
      rule: random


gateway:
  router:
    - id: product-service
      url: lb://PRODUCT-SERVICE
#      url: http://localhost:8081
      predicates:
        - Path=/product-server/**



    - id: order-service
      url: lb://ORDER-SERVICE
      predicates:
        -Path=/order-service/**