#spring:
#  application:
#    name: eureka-server

# (nested)
# more readable
# string, boolean, number
# lightweight
# list (-)

server:
  port: 8761

eureka:
  client:
#    server should not register itself as a server (client)
    register-with-eureka: false
#    prevent fetching its own service list
    fetch-registry: false